let newsObj = [ //news sources with relevant data
  {
    state: false,
    title: 'ABC(au)',
    link: 'abc-news-au',
    id: 'abcau',
    slider: 5,
  },
  {
    state: false,
    title: 'Al Jazeera',
    link: 'al-jazeera-english',
    id: 'aljaz',
    slider: 5,
  },
  {
    state: false,
    title: 'Ars Technica',
    link: 'ars-technica',
    id: 'arstech',
    slider: 5,
  },
  {
    state: false,
    title: 'Associated Press',
    link: 'associated-press',
    id: 'assocpress',
    slider: 5,
  },
  {
    state : false,
    title: 'BBC',
    link: 'bbc-news',
    id: 'bbc',
    slider: 5,
  },
  {
    state: false,
    title: 'BBC Sport',
    link: 'bbc-sport',
    id: 'bbcsp',
    slider: 5,
  },
  {
    state: false,
    title: 'Bild',
    link: 'bild',
    id: 'bild',
    slider: 5,
  },
  {
    state: false,
    title: 'Bloomberg',
    link: 'bloomberg',
    id: 'bloomberg',
    slider: 5,
  },
  {
    state: false,
    title: 'Breitbart News',
    link: 'breitbart-news',
    id: 'bild',
    slider: 5,
  },
  {
    state: false,
    title: 'Business Insider',
    link: 'business-insider',
    id: 'businsider',
    slider: 5,
  },
  {
    state: false,
    title: 'Business Insider(uk)',
    link: 'business-insider-uk',
    id: 'businsideruk',
    slider: 5,
  },
  {
    state: false,
    title: 'Buzzfeed',
    link: 'buzzfeed',
    id: 'buzzfeed',
    slider: 5,
  },
  {
    state: false,
    title: 'CNBC',
    link: 'cnbc',
    id: 'cnbc',
    slider: 5,
  },
  {
    state: false,
    title: 'CNN',
    link: 'cnn',
    id: 'cnn',
    slider: 5,
  },
  {
    state: false,
    title: 'Daily Mail',
    link: 'daily-mail',
    id: 'dailymail',
    slider: 5,
  },
  {
    state: false,
    title: 'Der Tagesspiegel',
    link: 'der-tagesspiegel',
    id: 'dertage',
    slider: 5,
  },
  {
    state: false,
    title: 'Die Zeit',
    link: 'die-zeit',
    id: 'diezeit',
    slider: 5,
  },
  {
    state: false,
    title: 'Engadget',
    link: 'engadget',
    id: 'engadget',
    slider: 5,
  },
  {
    state: false,
    title: 'Entertainment Weekly',
    link: 'entertainment-weekly',
    id: 'enterweekly',
    slider: 5,
  },
  {
    state: false,
    title: 'ESPN',
    link: 'espn',
    id: 'espn',
    slider: 5,
  },
  {
    state: false,
    title: 'ESPN Cric Info',
    link: 'espn-cric-info',
    id: 'espncric',
    slider: 5,
  },
  {
    state: false,
    title: 'Financial Times',
    link: 'financial-times',
    id: 'fintimes',
    slider: 5,
  },
  {
    state: false,
    title: 'Focus',
    link: 'focus',
    id: 'focus',
    slider: 5,
  },
  {
    state: false,
    title: 'Football Italia',
    link: 'football-italia',
    id: 'ftbitalia',
    slider: 5,
  },
  {
    state: false,
    title: 'Fortune',
    link: 'fortune',
    id: 'fortune',
    slider: 5,
  },
  {
    state: false,
    title: 'Four Four Two',
    link: 'four-four-two',
    id: 'fftwo',
    slider: 5,
  },
  {
    state: false,
    title: 'Fox Sports',
    link: 'fox-sports',
    id: 'foxsports',
    slider: 5,
  },
  {
    state: false,
    title: 'Google News',
    link: 'google-news',
    id: 'goognews',
    slider: 5,
  },
  {
    state: false,
    title: 'Gruenderszene',
    link: 'gruenderszene',
    id: 'gruenderszene',
    slider: 5,
  },
  {
    state: false,
    title: 'Hacker News',
    link: 'hacker-news',
    id: 'hackernews',
    slider: 5,
  },
  {
    state: false,
    title: 'Handelsblatt',
    link: 'handelsblatt',
    id: 'handelsblatt',
    slider: 5,
  },
  {
    state: false,
    title: 'IGN',
    link: 'ign',
    id: 'ign',
    slider: 5,
  },
  {
    state: false,
    title: 'Independent',
    link: 'independent',
    id: 'independent',
    slider: 5,
  },
  {
    state: false,
    title: 'Mashable',
    link: 'mashable',
    id: 'mashable',
    slider: 5,
  },
  {
    state: false,
    title: 'Metro',
    link: 'metro',
    id: 'metro',
    slider: 5,
  },
  {
    state: false,
    title: 'Mirror',
    link: 'mirror',
    id: 'mirror',
    slider: 5,
  },
  {
    state: false,
    title: 'MTV News',
    link: 'mtv-news',
    id: 'mtv',
    slider: 5,
  },
  {
    state: false,
    title: 'MTV News(uk)',
    link: 'mtv-news-uk',
    id: 'mtvuk',
    slider: 5,
  },
  {
    state: false,
    title: 'National Geographic',
    link: 'national-geographic',
    id: 'natgeo',
    slider: 5,
  },
  {
    state: false,
    title: 'New Scientist',
    link: 'new-scientist',
    id: 'newscientist',
    slider: 5,
  },
  {
    state: false,
    title: 'Newsweek',
    link: 'newsweek',
    id: 'newsweek',
    slider: 5,
  },
  {
    state: false,
    title: 'New York Magazine',
    link: 'new-york-magazine',
    id: 'nymagazine',
    slider: 5,
  },
  {
    state: false,
    title: 'NFL News',
    link: 'nfl-news',
    id: 'nfl',
    slider: 5,
  },
  {
    state: false,
    title: 'Polygon',
    link: 'polygon',
    id: 'polygon',
    slider: 5,
  },
  {
    state: false,
    title: 'Recode',
    link: 'recode',
    id: 'recode',
    slider: 5,
  },
  {
    state: false,
    title: 'Reddit /r/all',
    link: 'reddit-r-all',
    id: 'redditrall',
    slider: 5,
  },
  {
    state: false,
    title: 'Reuters',
    link: 'reuters',
    id: 'reuters',
    slider: 5,
  },
  {
    state: false,
    title: 'Spiegel Online',
    link: 'spiegel-online',
    id: 'spiegelonline',
    slider: 5,
  },
  {
    state: false,
    title: 'T3n',
    link: 't3n',
    id: 't3n',
    slider: 5,
  },
  {
    state: false,
    title: 'Talksport',
    link: 'talksport',
    id: 'talksport',
    slider: 5,
  },
  {
    state: false,
    title: 'TechCrunch',
    link: 'techcrunch',
    id: 'techcrunch',
    slider: 5,
  },
  {
    state: false,
    title: 'TechRadar',
    link: 'techradar',
    id: 'techradar',
    slider: 5,
  },
  {
    state: false,
    title: 'The Economist',
    link: 'the-economist',
    id: 'theeconomist',
    slider: 5,
  },
  {
    state: false,
    title: 'The Guardian(au)',
    link: 'the-guardian-au',
    id: 'theguardianau',
    slider: 5,
  },
  {
    state: false,
    title: 'The Guardian(uk)',
    link: 'the-guardian-uk',
    id: 'theguardianuk',
    slider: 5,
  },
  {
    state: false,
    title: 'The Hindu',
    link: 'the-hindu',
    id: 'thehindu',
    slider: 5,
  },
  {
    state: false,
    title: 'The Huffington Post',
    link: 'the-huffington-post',
    id: 'huffpost',
    slider: 5,
  },
  {
    state: false,
    title: 'The Lad Bible',
    link: 'the-lad-bible',
    id: 'ladbible',
    slider: 5,
  },
  {
    state : false,
    title: 'New York Times',
    link: 'the-new-york-times',
    id: 'nyt',
    slider: 5,
  },
  {
    state: false,
    title: 'The Next Web',
    link: 'the-next-web',
    id: 'thenextweb',
    slider: 5,
  },
  {
    state: false,
    title: 'The Sport Bible',
    link: 'the-sport-bible',
    id: 'thesportbible',
    slider: 5,
  },
  {
    state: false,
    title: 'The Telegraph',
    link: 'the-telegraph',
    id: 'thetelegraph',
    slider: 5,
  },
  {
    state: false,
    title: 'The Times of India',
    link: 'the-times-of-india',
    id: 'timesofindia',
    slider: 5,
  },
  {
    state: false,
    title: 'The Verge',
    link: 'the-verge',
    id: 'theverge',
    slider: 5,
  },
  {
    state: false,
    title: 'Wall Street Journal',
    link: 'the-wall-street-journal',
    id: 'wsj',
    slider: 5,
  },
  {
    state: false,
    title: 'The Washington Post',
    link: 'the-washington-post',
    id: 'washingtonpost',
    slider: 5,
  },
  {
    state: false,
    title: 'Time',
    link: 'time',
    id: 'time',
    slider: 5,
  },
  {
    state: false,
    title: 'USA Today',
    link: 'usa-today',
    id: 'usatoday',
    slider: 5,
  },
  {
    state: false,
    title: 'Wired.de',
    link: 'wired-de',
    id: 'wiredde',
    slider: 5,
  },
  {
    state: false,
    title: 'Wirtschafts Woche',
    link: 'wirtschafts-woche',
    id: 'wirtswoche',
    slider: 5,
  },
];
